Book es6 modules
2004-okari/AWESOME_BOOKS_ES6_MODULE pull request #1
Opened 2023-07-11 08:16 UTC by 2004-okari

.

2023-07-11 15:00 UTC, mckent05 requested changes
Hi  @2004-okari, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- Good job refactoring your project to use ES6 syntax 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
**OPTIONAL** - On page initial render, your application does not behave like a SPA as it renders all three sections. Please fix this 👍 👍 
Your app:
<img width="601" alt="hseheh" src="https://github.com/2004-okari/AWESOME_BOOKS_ES6_MODULE/assets/73607512/a3b60d08-d618-496b-aa8b-f66e0ff8ee22">

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-11 15:00 UTC, mckent05 commented on modules/singlePage.js
> +}
- Since this is a project that requires you to use the ES6 syntax, please use arrow functions for your initialize SPA function, please fix this 👍 👍

2023-07-12 13:21 UTC, alexander16108 requested changes
Hi @2004-okari , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/12rTjvF0ANQJsk/giphy.gif"/>

 ## Highlights
All linter checks are passing ✔️ ✔️
Your PR is professional 👍 👍
Good job refactoring your project to use ES6 syntax 👍

 ## Required Changes ♻️
_Check the comments under the review._

as suggested previously you are required to use the ES6 syntax, please use arrow functions for your initialize SPA function, please fix this 👍 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 13:21 UTC, alexander16108 commented on modules/singlePage.js
> +export default function initializeSPA() {
as suggested previously you are required to use the ES6 syntax, please use arrow functions for your initialize SPA function, please fix this 👍 👍

2023-07-12 16:50 UTC, hiromataba approved these changes
# Status: Approved :tada: :tada: :tada: 
Hi @2004-okari   :wave: :wave: 

![200w](https://user-images.githubusercontent.com/75126481/151663786-7e0aa330-6769-4ab2-a051-3754be515be9.gif)  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 19:33 UTC, merged